POST http://localhost:8080/conf
Content-Type: application/json

{
  "host": "<sshhost>",
  "user": "<ssh user>",
  "password": "<ssh password>",
  "port": <ssh port>,
  "tunnelLocalPort": <localport>,
  "tunnelRemoteHost": "<remote service host>",
  "tunnelRemotePort": <remote service port>
}



### GET request with parameter
GET http://localhost:8080/conflist
Accept: application/json